#!/usr/bin/env bash
# =============================================================================
# OpenClaw/Clawbot Docker Setup Script
# =============================================================================
# Automated setup for production deployment
# Usage: ./docker-setup.sh
# =============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script directory
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------

IMAGE_NAME="${OPENCLAW_IMAGE:-openclaw:local}"
COMPOSE_FILE="$ROOT_DIR/docker-compose.yml"
ENV_FILE="$ROOT_DIR/.env"
ENV_EXAMPLE="$ROOT_DIR/.env.example"

# Directories
OPENCLAW_CONFIG_DIR="${OPENCLAW_CONFIG_DIR:-$HOME/.openclaw}"
OPENCLAW_WORKSPACE_DIR="${OPENCLAW_WORKSPACE_DIR:-$HOME/.openclaw/workspace}"

# Ports
OPENCLAW_GATEWAY_PORT="${OPENCLAW_GATEWAY_PORT:-18789}"
OPENCLAW_GATEWAY_BIND="${OPENCLAW_GATEWAY_BIND:-lan}"

# Optional
OPENCLAW_DOCKER_APT_PACKAGES="${OPENCLAW_DOCKER_APT_PACKAGES:-}"
OPENCLAW_EXTRA_MOUNTS="${OPENCLAW_EXTRA_MOUNTS:-}"

# -----------------------------------------------------------------------------
# Helper Functions
# -----------------------------------------------------------------------------

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[OK]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

require_cmd() {
    if ! command -v "$1" >/dev/null 2>&1; then
        log_error "Missing dependency: $1"
        exit 1
    fi
}

generate_token() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    elif command -v python3 >/dev/null 2>&1; then
        python3 -c "import secrets; print(secrets.token_hex(32))"
    else
        # Fallback using /dev/urandom
        head -c 32 /dev/urandom | xxd -p | tr -d '\n'
    fi
}

# -----------------------------------------------------------------------------
# Pre-flight Checks
# -----------------------------------------------------------------------------

log_info "Checking dependencies..."

require_cmd docker

if ! docker compose version >/dev/null 2>&1; then
    log_error "Docker Compose not available (try: docker compose version)"
    exit 1
fi

log_success "Docker and Docker Compose are available"

# -----------------------------------------------------------------------------
# Directory Setup
# -----------------------------------------------------------------------------

log_info "Creating directories..."

mkdir -p "$OPENCLAW_CONFIG_DIR"
mkdir -p "$OPENCLAW_WORKSPACE_DIR"
mkdir -p "$OPENCLAW_CONFIG_DIR/agents"
mkdir -p "$OPENCLAW_CONFIG_DIR/sandboxes"

# Set ownership (for container user uid 1000)
if [[ "$EUID" -eq 0 ]]; then
    chown -R 1000:1000 "$OPENCLAW_CONFIG_DIR"
    chown -R 1000:1000 "$OPENCLAW_WORKSPACE_DIR"
fi

log_success "Directories created: $OPENCLAW_CONFIG_DIR"

# -----------------------------------------------------------------------------
# Environment Setup
# -----------------------------------------------------------------------------

log_info "Setting up environment..."

# Generate gateway token if not set
if [[ -z "${OPENCLAW_GATEWAY_TOKEN:-}" ]]; then
    OPENCLAW_GATEWAY_TOKEN="$(generate_token)"
    log_info "Generated new gateway token"
fi

# Create .env file if it doesn't exist
if [[ ! -f "$ENV_FILE" ]]; then
    if [[ -f "$ENV_EXAMPLE" ]]; then
        cp "$ENV_EXAMPLE" "$ENV_FILE"
        log_info "Created .env from .env.example"
    else
        cat > "$ENV_FILE" << EOF
# OpenClaw Environment Configuration
# Generated by docker-setup.sh

OPENCLAW_IMAGE=$IMAGE_NAME
OPENCLAW_CONFIG_DIR=$OPENCLAW_CONFIG_DIR
OPENCLAW_WORKSPACE_DIR=$OPENCLAW_WORKSPACE_DIR
OPENCLAW_GATEWAY_PORT=$OPENCLAW_GATEWAY_PORT
OPENCLAW_GATEWAY_BIND=$OPENCLAW_GATEWAY_BIND
OPENCLAW_GATEWAY_HOST=127.0.0.1
OPENCLAW_GATEWAY_TOKEN=$OPENCLAW_GATEWAY_TOKEN
OPENCLAW_DOCKER_APT_PACKAGES=$OPENCLAW_DOCKER_APT_PACKAGES
EOF
        log_info "Created new .env file"
    fi
fi

# Update token in .env
if grep -q "OPENCLAW_GATEWAY_TOKEN=CHANGE_ME" "$ENV_FILE" 2>/dev/null || \
   ! grep -q "OPENCLAW_GATEWAY_TOKEN=" "$ENV_FILE" 2>/dev/null; then
    if grep -q "OPENCLAW_GATEWAY_TOKEN=" "$ENV_FILE"; then
        sed -i.bak "s/OPENCLAW_GATEWAY_TOKEN=.*/OPENCLAW_GATEWAY_TOKEN=$OPENCLAW_GATEWAY_TOKEN/" "$ENV_FILE"
    else
        echo "OPENCLAW_GATEWAY_TOKEN=$OPENCLAW_GATEWAY_TOKEN" >> "$ENV_FILE"
    fi
    log_success "Gateway token configured"
fi

# Export for docker-compose
export OPENCLAW_IMAGE="$IMAGE_NAME"
export OPENCLAW_CONFIG_DIR
export OPENCLAW_WORKSPACE_DIR
export OPENCLAW_GATEWAY_PORT
export OPENCLAW_GATEWAY_BIND
export OPENCLAW_GATEWAY_TOKEN
export OPENCLAW_DOCKER_APT_PACKAGES

# -----------------------------------------------------------------------------
# Build Docker Images
# -----------------------------------------------------------------------------

log_info "Building Docker images..."

echo ""
echo "Building Gateway image: $IMAGE_NAME"
docker build \
    --build-arg "OPENCLAW_DOCKER_APT_PACKAGES=${OPENCLAW_DOCKER_APT_PACKAGES}" \
    -t "$IMAGE_NAME" \
    -f "$ROOT_DIR/Dockerfile" \
    "$ROOT_DIR"

log_success "Gateway image built"

echo ""
echo "Building Sandbox images..."
docker compose --profile setup build
log_success "Sandbox images built"

# -----------------------------------------------------------------------------
# Interactive Onboarding (Optional)
# -----------------------------------------------------------------------------

echo ""
echo "=============================================================="
echo " OpenClaw Setup Complete!"
echo "=============================================================="
echo ""
echo "Configuration:"
echo "  Config Directory: $OPENCLAW_CONFIG_DIR"
echo "  Workspace:        $OPENCLAW_WORKSPACE_DIR"
echo "  Gateway Port:     $OPENCLAW_GATEWAY_PORT"
echo "  Gateway Token:    $OPENCLAW_GATEWAY_TOKEN"
echo ""
echo "Next Steps:"
echo ""
echo "  1. Start the gateway:"
echo "     docker compose up -d openclaw-gateway"
echo ""
echo "  2. Check status:"
echo "     docker compose logs -f openclaw-gateway"
echo ""
echo "  3. Access Control UI:"
echo "     Open http://127.0.0.1:$OPENCLAW_GATEWAY_PORT/"
echo "     Paste your gateway token"
echo ""
echo "  4. (Optional) Run onboarding wizard:"
echo "     docker compose run --rm openclaw-cli onboard"
echo ""
echo "  5. (Optional) Configure channels:"
echo "     WhatsApp: docker compose run --rm openclaw-cli channels login"
echo "     Telegram: docker compose run --rm openclaw-cli channels add --channel telegram --token <token>"
echo ""
echo "  6. Health check:"
echo "     docker compose exec openclaw-gateway node dist/index.js health --token \"\$OPENCLAW_GATEWAY_TOKEN\""
echo ""
echo "=============================================================="

# -----------------------------------------------------------------------------
# Auto-start Gateway (optional)
# -----------------------------------------------------------------------------

read -p "Start the gateway now? [y/N] " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    log_info "Starting gateway..."
    docker compose up -d openclaw-gateway
    
    echo ""
    log_success "Gateway started!"
    echo ""
    echo "View logs: docker compose logs -f openclaw-gateway"
    echo "Access UI: http://127.0.0.1:$OPENCLAW_GATEWAY_PORT/"
fi
